# Site settings
title: CoderDojo Linz
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Die CoderDojo Gemeinschaft organisiert Programmierclubs für Kinder und Jugendliche zwischen 7 und 17 Jahren. Diese Seite ist für die CoderDojos Linz.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://coderdojo-linz.github.io" # the base hostname & protocol for your site
twitter_username: CoderDojoLinz
github_username:  CoderDojo-Linz

# Build settings
markdown: kramdown

exclude: ["bin", "bower_components", "jekyll", "node_modules", "obj", "styles/sass/*.*", "typings", "coderdojo-linz.*", "*.json", "app.*", "Gulpfile.js"]

#paginate: 3
#paginate_path: "blog/page:num"
